workflows:
  ahmad-ai-apk:
    name: Build Ahmad AI APK
    max_build_duration: 60
    
    environment:
      node: 22.11.0
      npm: 10
      java: 21  # ✅ Added Java 21
    
    scripts:
      - name: Install dependencies
        script: npm install
        
      - name: Build web assets
        script: npm run build
        
      - name: Setup Capacitor Android
        script: |
          npm install @capacitor/core @capacitor/cli @capacitor/android
          npx cap init AhmadAI com.ahmad.ai --web-dir dist
          npx cap add android
          npx cap sync
          
      - name: Build Release APK
        script: |
          cd android
          ./gradlew assembleRelease
    
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
    
    publishing:
      email:
        recipients:
          - your-email@gmail.com
        notify:
          success: true
          failure: true
